version: '2'

services:
  mongodb1:
    image: mongo
    container_name: mongodb.lotte.vn
#    network_mode: vietclidNet
    environment:
      - network.host=172.18.0.99
#      - http.port=9200
      - transport.host=172.18.0.99
#      - transport.tcp.port=9300
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
      - esdata2:/data/db
#      - esdata1:/usr/share/elasticsearch/data
#      - ./data/db:/data/db
    # A single value, analogous to its docker run counterpart.
    restart: always
#    expose:
#      - 3000
#      - 8000
#    ports:
#      - 9200:9200
#    networks:
#      - esnet
    expose:
      - "27017"
      - "28017"
    networks:
      vietclidNet:
        ipv4_address: 172.18.0.99
  elasticsearch1:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.1
    container_name: elasticsearch.lotte.vn
#    network_mode: vietclidNet
    environment:
      - network.host=172.18.0.98
      - http.port=9200
      - transport.host=172.18.0.98
      - transport.tcp.port=9300
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    # A single value, analogous to its docker run counterpart.
    restart: always
    expose:
      - "9200"
      - "9300"
#    expose:
#      - 3000
#      - 8000
#    ports:
#      - 9200:9200
#    networks:
#      - esnet
    networks:
      vietclidNet:
        ipv4_address: 172.18.0.98
  # Kibana dashboard for Elasticsearch data
#  kibana:
#    image: docker.elastic.co/kibana/kibana:5.6.1
#    container_name: kibana
#    restart: always
#    environment:
#      - LOGSPOUT=ignore  # don't send Kibana's logs to Logspout
##    environment:
#      - ELASTICSEARCH_URL=http://172.18.0.98:9200
#    links:
#      - elasticsearch1
#    depends_on:
#      - elasticsearch1
#    volumes:
#      - ./config/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
#      - kibanadata2:/etc/kibana
##  kibana:
##    image: docker.elastic.co/kibana/kibana:${ELASTIC_VER}
###    ports:
###      - "5601:5601"
##    links:
##      - elasticsearch1
#    networks:
#      vietclidNet:
#        ipv4_address: 172.18.0.96
#  mysql:
#    container_name: mysql
#    image: mysql:latest
#    restart: always
#    environment:
#      - MYSQL_ROOT_PASSWORD=root
#    ports:
#     - "3306:3306"
#    networks:
#      vpcbr:
#        ipv4_address: 10.5.0.5
#
#  apigw-tomcat:
#    container_name: apigw-tomcat
#    build: tomcat/.
#    ports:
#     - "8080:8080"
#     - "8009:8009"
#    networks:
#      vpcbr:
#        ipv4_address: 10.5.0.6
#    depends_on:
#     - mysql
volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local
  kibanadata2:
    driver: local
networks:
  vietclidNet:
    external: true
#    driver: bridge
#    ipam:
#     config:
#       - subnet: 172.19.0.0/16
#         gateway: 172.19.0.1
